// Copyright (c) 2018 Target Brands, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by gen-accessors; DO NOT EDIT.

package artifactory

// GetAPIKey returns the APIKey field if it's non-nil, zero value otherwise.
func (a *APIKey) GetAPIKey() string {
	if a == nil || a.APIKey == nil {
		return ""
	}
	return *a.APIKey
}

// GetLevel returns the Level field if it's non-nil, zero value otherwise.
func (a *ArtifactMessage) GetLevel() string {
	if a == nil || a.Level == nil {
		return ""
	}
	return *a.Level
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (a *ArtifactMessage) GetMessage() string {
	if a == nil || a.Message == nil {
		return ""
	}
	return *a.Message
}

// GetMessages returns the Messages field if it's non-nil, zero value otherwise.
func (a *Artifacts) GetMessages() []ArtifactMessage {
	if a == nil || a.Messages == nil {
		return nil
	}
	return *a.Messages
}

// GetArtifactsCount returns the ArtifactsCount field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetArtifactsCount() string {
	if b == nil || b.ArtifactsCount == nil {
		return ""
	}
	return *b.ArtifactsCount
}

// GetArtifactsSize returns the ArtifactsSize field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetArtifactsSize() string {
	if b == nil || b.ArtifactsSize == nil {
		return ""
	}
	return *b.ArtifactsSize
}

// GetBinariesCount returns the BinariesCount field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetBinariesCount() string {
	if b == nil || b.BinariesCount == nil {
		return ""
	}
	return *b.BinariesCount
}

// GetBinariesSize returns the BinariesSize field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetBinariesSize() string {
	if b == nil || b.BinariesSize == nil {
		return ""
	}
	return *b.BinariesSize
}

// GetItemsCount returns the ItemsCount field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetItemsCount() string {
	if b == nil || b.ItemsCount == nil {
		return ""
	}
	return *b.ItemsCount
}

// GetOptimization returns the Optimization field if it's non-nil, zero value otherwise.
func (b *BinariesSummary) GetOptimization() string {
	if b == nil || b.Optimization == nil {
		return ""
	}
	return *b.Optimization
}

// GetMD5 returns the MD5 field if it's non-nil, zero value otherwise.
func (c *Checksums) GetMD5() string {
	if c == nil || c.MD5 == nil {
		return ""
	}
	return *c.MD5
}

// GetSHA1 returns the SHA1 field if it's non-nil, zero value otherwise.
func (c *Checksums) GetSHA1() string {
	if c == nil || c.SHA1 == nil {
		return ""
	}
	return *c.SHA1
}

// GetSHA256 returns the SHA256 field if it's non-nil, zero value otherwise.
func (c *Checksums) GetSHA256() string {
	if c == nil || c.SHA256 == nil {
		return ""
	}
	return *c.SHA256
}

// GetFolder returns the Folder field if it's non-nil, zero value otherwise.
func (c *Child) GetFolder() string {
	if c == nil || c.Folder == nil {
		return ""
	}
	return *c.Folder
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (c *Child) GetURI() string {
	if c == nil || c.URI == nil {
		return ""
	}
	return *c.URI
}

// GetInfo returns the Info field if it's non-nil, zero value otherwise.
func (d *DeleteAPIKey) GetInfo() string {
	if d == nil || d.Info == nil {
		return ""
	}
	return *d.Info
}

// GetPrincipals returns the Principals field.
func (e *EffectiveItemPermissions) GetPrincipals() *Principals {
	if e == nil {
		return nil
	}
	return e.Principals
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (e *EffectiveItemPermissions) GetURI() string {
	if e == nil || e.URI == nil {
		return ""
	}
	return *e.URI
}

// GetChecksums returns the Checksums field.
func (f *File) GetChecksums() *Checksums {
	if f == nil {
		return nil
	}
	return f.Checksums
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (f *File) GetCreated() Timestamp {
	if f == nil || f.Created == nil {
		return Timestamp{}
	}
	return *f.Created
}

// GetCreatedBy returns the CreatedBy field if it's non-nil, zero value otherwise.
func (f *File) GetCreatedBy() string {
	if f == nil || f.CreatedBy == nil {
		return ""
	}
	return *f.CreatedBy
}

// GetDownloadURI returns the DownloadURI field if it's non-nil, zero value otherwise.
func (f *File) GetDownloadURI() string {
	if f == nil || f.DownloadURI == nil {
		return ""
	}
	return *f.DownloadURI
}

// GetLastModified returns the LastModified field if it's non-nil, zero value otherwise.
func (f *File) GetLastModified() Timestamp {
	if f == nil || f.LastModified == nil {
		return Timestamp{}
	}
	return *f.LastModified
}

// GetLastUpdated returns the LastUpdated field if it's non-nil, zero value otherwise.
func (f *File) GetLastUpdated() Timestamp {
	if f == nil || f.LastUpdated == nil {
		return Timestamp{}
	}
	return *f.LastUpdated
}

// GetMimeType returns the MimeType field if it's non-nil, zero value otherwise.
func (f *File) GetMimeType() string {
	if f == nil || f.MimeType == nil {
		return ""
	}
	return *f.MimeType
}

// GetModifiedBy returns the ModifiedBy field if it's non-nil, zero value otherwise.
func (f *File) GetModifiedBy() string {
	if f == nil || f.ModifiedBy == nil {
		return ""
	}
	return *f.ModifiedBy
}

// GetOriginalChecksums returns the OriginalChecksums field.
func (f *File) GetOriginalChecksums() *Checksums {
	if f == nil {
		return nil
	}
	return f.OriginalChecksums
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (f *File) GetPath() string {
	if f == nil || f.Path == nil {
		return ""
	}
	return *f.Path
}

// GetRemoteURL returns the RemoteURL field if it's non-nil, zero value otherwise.
func (f *File) GetRemoteURL() string {
	if f == nil || f.RemoteURL == nil {
		return ""
	}
	return *f.RemoteURL
}

// GetRepo returns the Repo field if it's non-nil, zero value otherwise.
func (f *File) GetRepo() string {
	if f == nil || f.Repo == nil {
		return ""
	}
	return *f.Repo
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (f *File) GetSize() string {
	if f == nil || f.Size == nil {
		return ""
	}
	return *f.Size
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (f *File) GetURI() string {
	if f == nil || f.URI == nil {
		return ""
	}
	return *f.URI
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (f *FileList) GetCreated() Timestamp {
	if f == nil || f.Created == nil {
		return Timestamp{}
	}
	return *f.Created
}

// GetFiles returns the Files field if it's non-nil, zero value otherwise.
func (f *FileList) GetFiles() []FileListItem {
	if f == nil || f.Files == nil {
		return nil
	}
	return *f.Files
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (f *FileList) GetURI() string {
	if f == nil || f.URI == nil {
		return ""
	}
	return *f.URI
}

// GetFolder returns the Folder field if it's non-nil, zero value otherwise.
func (f *FileListItem) GetFolder() bool {
	if f == nil || f.Folder == nil {
		return false
	}
	return *f.Folder
}

// GetLastModified returns the LastModified field if it's non-nil, zero value otherwise.
func (f *FileListItem) GetLastModified() Timestamp {
	if f == nil || f.LastModified == nil {
		return Timestamp{}
	}
	return *f.LastModified
}

// GetSHA1 returns the SHA1 field if it's non-nil, zero value otherwise.
func (f *FileListItem) GetSHA1() string {
	if f == nil || f.SHA1 == nil {
		return ""
	}
	return *f.SHA1
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (f *FileListItem) GetSize() int {
	if f == nil || f.Size == nil {
		return 0
	}
	return *f.Size
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (f *FileListItem) GetURI() string {
	if f == nil || f.URI == nil {
		return ""
	}
	return *f.URI
}

// GetDownloadCount returns the DownloadCount field if it's non-nil, zero value otherwise.
func (f *FileStatistics) GetDownloadCount() int {
	if f == nil || f.DownloadCount == nil {
		return 0
	}
	return *f.DownloadCount
}

// GetLastDownloaded returns the LastDownloaded field if it's non-nil, zero value otherwise.
func (f *FileStatistics) GetLastDownloaded() Timestamp {
	if f == nil || f.LastDownloaded == nil {
		return Timestamp{}
	}
	return *f.LastDownloaded
}

// GetLastDownloadedBy returns the LastDownloadedBy field if it's non-nil, zero value otherwise.
func (f *FileStatistics) GetLastDownloadedBy() string {
	if f == nil || f.LastDownloadedBy == nil {
		return ""
	}
	return *f.LastDownloadedBy
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (f *FileStatistics) GetURI() string {
	if f == nil || f.URI == nil {
		return ""
	}
	return *f.URI
}

// GetFreeSpace returns the FreeSpace field if it's non-nil, zero value otherwise.
func (f *FileStoreSummary) GetFreeSpace() string {
	if f == nil || f.FreeSpace == nil {
		return ""
	}
	return *f.FreeSpace
}

// GetStorageDirectory returns the StorageDirectory field if it's non-nil, zero value otherwise.
func (f *FileStoreSummary) GetStorageDirectory() string {
	if f == nil || f.StorageDirectory == nil {
		return ""
	}
	return *f.StorageDirectory
}

// GetStorageType returns the StorageType field if it's non-nil, zero value otherwise.
func (f *FileStoreSummary) GetStorageType() string {
	if f == nil || f.StorageType == nil {
		return ""
	}
	return *f.StorageType
}

// GetTotalSpace returns the TotalSpace field if it's non-nil, zero value otherwise.
func (f *FileStoreSummary) GetTotalSpace() string {
	if f == nil || f.TotalSpace == nil {
		return ""
	}
	return *f.TotalSpace
}

// GetUsedSpace returns the UsedSpace field if it's non-nil, zero value otherwise.
func (f *FileStoreSummary) GetUsedSpace() string {
	if f == nil || f.UsedSpace == nil {
		return ""
	}
	return *f.UsedSpace
}

// GetChildren returns the Children field if it's non-nil, zero value otherwise.
func (f *Folder) GetChildren() []Child {
	if f == nil || f.Children == nil {
		return nil
	}
	return *f.Children
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (f *Folder) GetCreated() Timestamp {
	if f == nil || f.Created == nil {
		return Timestamp{}
	}
	return *f.Created
}

// GetCreatedBy returns the CreatedBy field if it's non-nil, zero value otherwise.
func (f *Folder) GetCreatedBy() string {
	if f == nil || f.CreatedBy == nil {
		return ""
	}
	return *f.CreatedBy
}

// GetLastModified returns the LastModified field if it's non-nil, zero value otherwise.
func (f *Folder) GetLastModified() Timestamp {
	if f == nil || f.LastModified == nil {
		return Timestamp{}
	}
	return *f.LastModified
}

// GetLastUpdated returns the LastUpdated field if it's non-nil, zero value otherwise.
func (f *Folder) GetLastUpdated() Timestamp {
	if f == nil || f.LastUpdated == nil {
		return Timestamp{}
	}
	return *f.LastUpdated
}

// GetModifiedBy returns the ModifiedBy field if it's non-nil, zero value otherwise.
func (f *Folder) GetModifiedBy() string {
	if f == nil || f.ModifiedBy == nil {
		return ""
	}
	return *f.ModifiedBy
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (f *Folder) GetPath() string {
	if f == nil || f.Path == nil {
		return ""
	}
	return *f.Path
}

// GetRepo returns the Repo field if it's non-nil, zero value otherwise.
func (f *Folder) GetRepo() string {
	if f == nil || f.Repo == nil {
		return ""
	}
	return *f.Repo
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (f *Folder) GetURI() string {
	if f == nil || f.URI == nil {
		return ""
	}
	return *f.URI
}

// GetArtifactID returns the ArtifactID field if it's non-nil, zero value otherwise.
func (g *GAVCRequest) GetArtifactID() string {
	if g == nil || g.ArtifactID == nil {
		return ""
	}
	return *g.ArtifactID
}

// GetClassifier returns the Classifier field if it's non-nil, zero value otherwise.
func (g *GAVCRequest) GetClassifier() string {
	if g == nil || g.Classifier == nil {
		return ""
	}
	return *g.Classifier
}

// GetGroupID returns the GroupID field if it's non-nil, zero value otherwise.
func (g *GAVCRequest) GetGroupID() string {
	if g == nil || g.GroupID == nil {
		return ""
	}
	return *g.GroupID
}

// GetRepos returns the Repos field if it's non-nil, zero value otherwise.
func (g *GAVCRequest) GetRepos() []string {
	if g == nil || g.Repos == nil {
		return nil
	}
	return *g.Repos
}

// GetVersion returns the Version field if it's non-nil, zero value otherwise.
func (g *GAVCRequest) GetVersion() string {
	if g == nil || g.Version == nil {
		return ""
	}
	return *g.Version
}

// GetResults returns the Results field if it's non-nil, zero value otherwise.
func (g *GAVCResponse) GetResults() []File {
	if g == nil || g.Results == nil {
		return nil
	}
	return *g.Results
}

// GetBlackedOut returns the BlackedOut field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetBlackedOut() bool {
	if g == nil || g.BlackedOut == nil {
		return false
	}
	return *g.BlackedOut
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetDescription() string {
	if g == nil || g.Description == nil {
		return ""
	}
	return *g.Description
}

// GetExcludesPattern returns the ExcludesPattern field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetExcludesPattern() string {
	if g == nil || g.ExcludesPattern == nil {
		return ""
	}
	return *g.ExcludesPattern
}

// GetHandleReleases returns the HandleReleases field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetHandleReleases() bool {
	if g == nil || g.HandleReleases == nil {
		return false
	}
	return *g.HandleReleases
}

// GetHandleSnapshots returns the HandleSnapshots field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetHandleSnapshots() bool {
	if g == nil || g.HandleSnapshots == nil {
		return false
	}
	return *g.HandleSnapshots
}

// GetIncludesPattern returns the IncludesPattern field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetIncludesPattern() string {
	if g == nil || g.IncludesPattern == nil {
		return ""
	}
	return *g.IncludesPattern
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetKey() string {
	if g == nil || g.Key == nil {
		return ""
	}
	return *g.Key
}

// GetLayoutRef returns the LayoutRef field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetLayoutRef() string {
	if g == nil || g.LayoutRef == nil {
		return ""
	}
	return *g.LayoutRef
}

// GetMaxUniqueSnapshots returns the MaxUniqueSnapshots field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetMaxUniqueSnapshots() int {
	if g == nil || g.MaxUniqueSnapshots == nil {
		return 0
	}
	return *g.MaxUniqueSnapshots
}

// GetNotes returns the Notes field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetNotes() string {
	if g == nil || g.Notes == nil {
		return ""
	}
	return *g.Notes
}

// GetPackageType returns the PackageType field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetPackageType() string {
	if g == nil || g.PackageType == nil {
		return ""
	}
	return *g.PackageType
}

// GetPropertySets returns the PropertySets field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetPropertySets() []string {
	if g == nil || g.PropertySets == nil {
		return nil
	}
	return *g.PropertySets
}

// GetRClass returns the RClass field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetRClass() string {
	if g == nil || g.RClass == nil {
		return ""
	}
	return *g.RClass
}

// GetSuppressPomConsistencyChecks returns the SuppressPomConsistencyChecks field if it's non-nil, zero value otherwise.
func (g *GenericRepository) GetSuppressPomConsistencyChecks() bool {
	if g == nil || g.SuppressPomConsistencyChecks == nil {
		return false
	}
	return *g.SuppressPomConsistencyChecks
}

// GetAdminPrivileges returns the AdminPrivileges field if it's non-nil, zero value otherwise.
func (g *Group) GetAdminPrivileges() bool {
	if g == nil || g.AdminPrivileges == nil {
		return false
	}
	return *g.AdminPrivileges
}

// GetAutoJoin returns the AutoJoin field if it's non-nil, zero value otherwise.
func (g *Group) GetAutoJoin() bool {
	if g == nil || g.AutoJoin == nil {
		return false
	}
	return *g.AutoJoin
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (g *Group) GetDescription() string {
	if g == nil || g.Description == nil {
		return ""
	}
	return *g.Description
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (g *Group) GetName() string {
	if g == nil || g.Name == nil {
		return ""
	}
	return *g.Name
}

// GetRealm returns the Realm field if it's non-nil, zero value otherwise.
func (g *Group) GetRealm() string {
	if g == nil || g.Realm == nil {
		return ""
	}
	return *g.Realm
}

// GetRealmAttributes returns the RealmAttributes field if it's non-nil, zero value otherwise.
func (g *Group) GetRealmAttributes() string {
	if g == nil || g.RealmAttributes == nil {
		return ""
	}
	return *g.RealmAttributes
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (g *Group) GetURI() string {
	if g == nil || g.URI == nil {
		return ""
	}
	return *g.URI
}

// GetExpired returns the Expired field if it's non-nil, zero value otherwise.
func (h *HALicense) GetExpired() bool {
	if h == nil || h.Expired == nil {
		return false
	}
	return *h.Expired
}

// GetLicensedTo returns the LicensedTo field if it's non-nil, zero value otherwise.
func (h *HALicense) GetLicensedTo() string {
	if h == nil || h.LicensedTo == nil {
		return ""
	}
	return *h.LicensedTo
}

// GetLicenseHash returns the LicenseHash field if it's non-nil, zero value otherwise.
func (h *HALicense) GetLicenseHash() string {
	if h == nil || h.LicenseHash == nil {
		return ""
	}
	return *h.LicenseHash
}

// GetNodeID returns the NodeID field if it's non-nil, zero value otherwise.
func (h *HALicense) GetNodeID() string {
	if h == nil || h.NodeID == nil {
		return ""
	}
	return *h.NodeID
}

// GetNodeURL returns the NodeURL field if it's non-nil, zero value otherwise.
func (h *HALicense) GetNodeURL() string {
	if h == nil || h.NodeURL == nil {
		return ""
	}
	return *h.NodeURL
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (h *HALicense) GetType() string {
	if h == nil || h.Type == nil {
		return ""
	}
	return *h.Type
}

// GetValidThrough returns the ValidThrough field if it's non-nil, zero value otherwise.
func (h *HALicense) GetValidThrough() string {
	if h == nil || h.ValidThrough == nil {
		return ""
	}
	return *h.ValidThrough
}

// GetMessages returns the Messages field if it's non-nil, zero value otherwise.
func (h *HALicenseResponse) GetMessages() map[string]string {
	if h == nil || h.Messages == nil {
		return map[string]string{}
	}
	return *h.Messages
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (h *HALicenseResponse) GetStatus() int {
	if h == nil || h.Status == nil {
		return 0
	}
	return *h.Status
}

// GetLicenses returns the Licenses field if it's non-nil, zero value otherwise.
func (h *HALicenses) GetLicenses() []HALicense {
	if h == nil || h.Licenses == nil {
		return nil
	}
	return *h.Licenses
}

// GetCopy returns the Copy field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetCopy() bool {
	if i == nil || i.Copy == nil {
		return false
	}
	return *i.Copy
}

// GetDockerRepository returns the DockerRepository field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetDockerRepository() string {
	if i == nil || i.DockerRepository == nil {
		return ""
	}
	return *i.DockerRepository
}

// GetTag returns the Tag field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetTag() string {
	if i == nil || i.Tag == nil {
		return ""
	}
	return *i.Tag
}

// GetTargetDockerRepository returns the TargetDockerRepository field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetTargetDockerRepository() string {
	if i == nil || i.TargetDockerRepository == nil {
		return ""
	}
	return *i.TargetDockerRepository
}

// GetTargetRepo returns the TargetRepo field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetTargetRepo() string {
	if i == nil || i.TargetRepo == nil {
		return ""
	}
	return *i.TargetRepo
}

// GetTargetTag returns the TargetTag field if it's non-nil, zero value otherwise.
func (i *ImagePromotion) GetTargetTag() string {
	if i == nil || i.TargetTag == nil {
		return ""
	}
	return *i.TargetTag
}

// GetLastModified returns the LastModified field if it's non-nil, zero value otherwise.
func (i *ItemLastModified) GetLastModified() Timestamp {
	if i == nil || i.LastModified == nil {
		return Timestamp{}
	}
	return *i.LastModified
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (i *ItemLastModified) GetURI() string {
	if i == nil || i.URI == nil {
		return ""
	}
	return *i.URI
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (i *ItemProperties) GetURI() string {
	if i == nil || i.URI == nil {
		return ""
	}
	return *i.URI
}

// GetLicensedTo returns the LicensedTo field if it's non-nil, zero value otherwise.
func (l *License) GetLicensedTo() string {
	if l == nil || l.LicensedTo == nil {
		return ""
	}
	return *l.LicensedTo
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (l *License) GetType() string {
	if l == nil || l.Type == nil {
		return ""
	}
	return *l.Type
}

// GetValidThrough returns the ValidThrough field if it's non-nil, zero value otherwise.
func (l *License) GetValidThrough() string {
	if l == nil || l.ValidThrough == nil {
		return ""
	}
	return *l.ValidThrough
}

// GetLicenseHashes returns the LicenseHashes field if it's non-nil, zero value otherwise.
func (l *LicenseRemoval) GetLicenseHashes() []string {
	if l == nil || l.LicenseHashes == nil {
		return nil
	}
	return *l.LicenseHashes
}

// GetLicenseKey returns the LicenseKey field if it's non-nil, zero value otherwise.
func (l *LicenseRequest) GetLicenseKey() string {
	if l == nil || l.LicenseKey == nil {
		return ""
	}
	return *l.LicenseKey
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (l *LicenseResponse) GetMessage() string {
	if l == nil || l.Message == nil {
		return ""
	}
	return *l.Message
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (l *LicenseResponse) GetStatus() int {
	if l == nil || l.Status == nil {
		return 0
	}
	return *l.Status
}

// GetArchiveBrowsingEnabled returns the ArchiveBrowsingEnabled field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetArchiveBrowsingEnabled() bool {
	if l == nil || l.ArchiveBrowsingEnabled == nil {
		return false
	}
	return *l.ArchiveBrowsingEnabled
}

// GetCalculateYumMetadata returns the CalculateYumMetadata field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetCalculateYumMetadata() bool {
	if l == nil || l.CalculateYumMetadata == nil {
		return false
	}
	return *l.CalculateYumMetadata
}

// GetChecksumPolicyType returns the ChecksumPolicyType field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetChecksumPolicyType() string {
	if l == nil || l.ChecksumPolicyType == nil {
		return ""
	}
	return *l.ChecksumPolicyType
}

// GetDebianTrivialLayout returns the DebianTrivialLayout field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetDebianTrivialLayout() bool {
	if l == nil || l.DebianTrivialLayout == nil {
		return false
	}
	return *l.DebianTrivialLayout
}

// GetDockerAPIVersion returns the DockerAPIVersion field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetDockerAPIVersion() string {
	if l == nil || l.DockerAPIVersion == nil {
		return ""
	}
	return *l.DockerAPIVersion
}

// GetEnableFileListsIndexing returns the EnableFileListsIndexing field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetEnableFileListsIndexing() bool {
	if l == nil || l.EnableFileListsIndexing == nil {
		return false
	}
	return *l.EnableFileListsIndexing
}

// GetMaxUniqueTags returns the MaxUniqueTags field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetMaxUniqueTags() int {
	if l == nil || l.MaxUniqueTags == nil {
		return 0
	}
	return *l.MaxUniqueTags
}

// GetOptionalIndexCompressionFormats returns the OptionalIndexCompressionFormats field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetOptionalIndexCompressionFormats() []string {
	if l == nil || l.OptionalIndexCompressionFormats == nil {
		return nil
	}
	return *l.OptionalIndexCompressionFormats
}

// GetSnapshotVersionBehavior returns the SnapshotVersionBehavior field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetSnapshotVersionBehavior() string {
	if l == nil || l.SnapshotVersionBehavior == nil {
		return ""
	}
	return *l.SnapshotVersionBehavior
}

// GetYumRootDepth returns the YumRootDepth field if it's non-nil, zero value otherwise.
func (l *LocalRepository) GetYumRootDepth() int {
	if l == nil || l.YumRootDepth == nil {
		return 0
	}
	return *l.YumRootDepth
}

// GetExcludesPattern returns the ExcludesPattern field if it's non-nil, zero value otherwise.
func (p *PermissionTarget) GetExcludesPattern() string {
	if p == nil || p.ExcludesPattern == nil {
		return ""
	}
	return *p.ExcludesPattern
}

// GetIncludesPattern returns the IncludesPattern field if it's non-nil, zero value otherwise.
func (p *PermissionTarget) GetIncludesPattern() string {
	if p == nil || p.IncludesPattern == nil {
		return ""
	}
	return *p.IncludesPattern
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *PermissionTarget) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetPrincipals returns the Principals field.
func (p *PermissionTarget) GetPrincipals() *Principals {
	if p == nil {
		return nil
	}
	return p.Principals
}

// GetRepositories returns the Repositories field if it's non-nil, zero value otherwise.
func (p *PermissionTarget) GetRepositories() []string {
	if p == nil || p.Repositories == nil {
		return nil
	}
	return *p.Repositories
}

// GetURI returns the URI field if it's non-nil, zero value otherwise.
func (p *PermissionTarget) GetURI() string {
	if p == nil || p.URI == nil {
		return ""
	}
	return *p.URI
}

// GetRepositories returns the Repositories field if it's non-nil, zero value otherwise.
func (r *Registry) GetRepositories() []string {
	if r == nil || r.Repositories == nil {
		return nil
	}
	return *r.Repositories
}

// GetAllowAnyHostAuth returns the AllowAnyHostAuth field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetAllowAnyHostAuth() bool {
	if r == nil || r.AllowAnyHostAuth == nil {
		return false
	}
	return *r.AllowAnyHostAuth
}

// GetAssumedOfflinePeriodSecs returns the AssumedOfflinePeriodSecs field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetAssumedOfflinePeriodSecs() int {
	if r == nil || r.AssumedOfflinePeriodSecs == nil {
		return 0
	}
	return *r.AssumedOfflinePeriodSecs
}

// GetBlockMismatchingMimeTypes returns the BlockMismatchingMimeTypes field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetBlockMismatchingMimeTypes() bool {
	if r == nil || r.BlockMismatchingMimeTypes == nil {
		return false
	}
	return *r.BlockMismatchingMimeTypes
}

// GetBowerRegistryURL returns the BowerRegistryURL field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetBowerRegistryURL() string {
	if r == nil || r.BowerRegistryURL == nil {
		return ""
	}
	return *r.BowerRegistryURL
}

// GetBypassHeadRequest returns the BypassHeadRequest field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetBypassHeadRequest() bool {
	if r == nil || r.BypassHeadRequest == nil {
		return false
	}
	return *r.BypassHeadRequest
}

// GetClientTLSCertificate returns the ClientTLSCertificate field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetClientTLSCertificate() string {
	if r == nil || r.ClientTLSCertificate == nil {
		return ""
	}
	return *r.ClientTLSCertificate
}

// GetComposerRegistryURL returns the ComposerRegistryURL field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetComposerRegistryURL() string {
	if r == nil || r.ComposerRegistryURL == nil {
		return ""
	}
	return *r.ComposerRegistryURL
}

// GetEnableCookieManagement returns the EnableCookieManagement field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetEnableCookieManagement() bool {
	if r == nil || r.EnableCookieManagement == nil {
		return false
	}
	return *r.EnableCookieManagement
}

// GetFailedRetrievalCachePeriodSecs returns the FailedRetrievalCachePeriodSecs field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetFailedRetrievalCachePeriodSecs() int {
	if r == nil || r.FailedRetrievalCachePeriodSecs == nil {
		return 0
	}
	return *r.FailedRetrievalCachePeriodSecs
}

// GetFetchJarsEagerly returns the FetchJarsEagerly field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetFetchJarsEagerly() bool {
	if r == nil || r.FetchJarsEagerly == nil {
		return false
	}
	return *r.FetchJarsEagerly
}

// GetFetchSourcesEagerly returns the FetchSourcesEagerly field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetFetchSourcesEagerly() bool {
	if r == nil || r.FetchSourcesEagerly == nil {
		return false
	}
	return *r.FetchSourcesEagerly
}

// GetHardFail returns the HardFail field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetHardFail() bool {
	if r == nil || r.HardFail == nil {
		return false
	}
	return *r.HardFail
}

// GetLocalAddress returns the LocalAddress field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetLocalAddress() string {
	if r == nil || r.LocalAddress == nil {
		return ""
	}
	return *r.LocalAddress
}

// GetMissedRetrievalCachePeriodSecs returns the MissedRetrievalCachePeriodSecs field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetMissedRetrievalCachePeriodSecs() int {
	if r == nil || r.MissedRetrievalCachePeriodSecs == nil {
		return 0
	}
	return *r.MissedRetrievalCachePeriodSecs
}

// GetOffline returns the Offline field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetOffline() bool {
	if r == nil || r.Offline == nil {
		return false
	}
	return *r.Offline
}

// GetPassword returns the Password field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetPassword() string {
	if r == nil || r.Password == nil {
		return ""
	}
	return *r.Password
}

// GetProxy returns the Proxy field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetProxy() string {
	if r == nil || r.Proxy == nil {
		return ""
	}
	return *r.Proxy
}

// GetPyPIRegistryURL returns the PyPIRegistryURL field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetPyPIRegistryURL() string {
	if r == nil || r.PyPIRegistryURL == nil {
		return ""
	}
	return *r.PyPIRegistryURL
}

// GetRemoteRepoChecksumPolicyType returns the RemoteRepoChecksumPolicyType field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetRemoteRepoChecksumPolicyType() string {
	if r == nil || r.RemoteRepoChecksumPolicyType == nil {
		return ""
	}
	return *r.RemoteRepoChecksumPolicyType
}

// GetRetrievalCachePeriodSecs returns the RetrievalCachePeriodSecs field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetRetrievalCachePeriodSecs() int {
	if r == nil || r.RetrievalCachePeriodSecs == nil {
		return 0
	}
	return *r.RetrievalCachePeriodSecs
}

// GetShareConfiguration returns the ShareConfiguration field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetShareConfiguration() bool {
	if r == nil || r.ShareConfiguration == nil {
		return false
	}
	return *r.ShareConfiguration
}

// GetSocketTimeoutMillis returns the SocketTimeoutMillis field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetSocketTimeoutMillis() int {
	if r == nil || r.SocketTimeoutMillis == nil {
		return 0
	}
	return *r.SocketTimeoutMillis
}

// GetStoreArtifactsLocally returns the StoreArtifactsLocally field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetStoreArtifactsLocally() bool {
	if r == nil || r.StoreArtifactsLocally == nil {
		return false
	}
	return *r.StoreArtifactsLocally
}

// GetSynchronizeProperties returns the SynchronizeProperties field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetSynchronizeProperties() bool {
	if r == nil || r.SynchronizeProperties == nil {
		return false
	}
	return *r.SynchronizeProperties
}

// GetUnusedArtifactsCleanupEnabled returns the UnusedArtifactsCleanupEnabled field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetUnusedArtifactsCleanupEnabled() bool {
	if r == nil || r.UnusedArtifactsCleanupEnabled == nil {
		return false
	}
	return *r.UnusedArtifactsCleanupEnabled
}

// GetUnusedArtifactsCleanupPeriodHours returns the UnusedArtifactsCleanupPeriodHours field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetUnusedArtifactsCleanupPeriodHours() int {
	if r == nil || r.UnusedArtifactsCleanupPeriodHours == nil {
		return 0
	}
	return *r.UnusedArtifactsCleanupPeriodHours
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetURL() string {
	if r == nil || r.URL == nil {
		return ""
	}
	return *r.URL
}

// GetUsername returns the Username field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetUsername() string {
	if r == nil || r.Username == nil {
		return ""
	}
	return *r.Username
}

// GetVcsGitDownloadUrl returns the VcsGitDownloadUrl field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetVcsGitDownloadUrl() string {
	if r == nil || r.VcsGitDownloadUrl == nil {
		return ""
	}
	return *r.VcsGitDownloadUrl
}

// GetVcsGitProvider returns the VcsGitProvider field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetVcsGitProvider() string {
	if r == nil || r.VcsGitProvider == nil {
		return ""
	}
	return *r.VcsGitProvider
}

// GetVcsType returns the VcsType field if it's non-nil, zero value otherwise.
func (r *RemoteRepository) GetVcsType() string {
	if r == nil || r.VcsType == nil {
		return ""
	}
	return *r.VcsType
}

// GetFilesCount returns the FilesCount field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetFilesCount() int {
	if r == nil || r.FilesCount == nil {
		return 0
	}
	return *r.FilesCount
}

// GetFoldersCount returns the FoldersCount field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetFoldersCount() int {
	if r == nil || r.FoldersCount == nil {
		return 0
	}
	return *r.FoldersCount
}

// GetItemsCount returns the ItemsCount field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetItemsCount() int {
	if r == nil || r.ItemsCount == nil {
		return 0
	}
	return *r.ItemsCount
}

// GetPackageType returns the PackageType field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetPackageType() string {
	if r == nil || r.PackageType == nil {
		return ""
	}
	return *r.PackageType
}

// GetPercentage returns the Percentage field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetPercentage() string {
	if r == nil || r.Percentage == nil {
		return ""
	}
	return *r.Percentage
}

// GetRepoKey returns the RepoKey field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetRepoKey() string {
	if r == nil || r.RepoKey == nil {
		return ""
	}
	return *r.RepoKey
}

// GetRepoType returns the RepoType field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetRepoType() string {
	if r == nil || r.RepoType == nil {
		return ""
	}
	return *r.RepoType
}

// GetUsedSpace returns the UsedSpace field if it's non-nil, zero value otherwise.
func (r *RepositoriesSummary) GetUsedSpace() string {
	if r == nil || r.UsedSpace == nil {
		return ""
	}
	return *r.UsedSpace
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (r *Repository) GetDescription() string {
	if r == nil || r.Description == nil {
		return ""
	}
	return *r.Description
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (r *Repository) GetKey() string {
	if r == nil || r.Key == nil {
		return ""
	}
	return *r.Key
}

// GetPackageType returns the PackageType field if it's non-nil, zero value otherwise.
func (r *Repository) GetPackageType() string {
	if r == nil || r.PackageType == nil {
		return ""
	}
	return *r.PackageType
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (r *Repository) GetType() string {
	if r == nil || r.Type == nil {
		return ""
	}
	return *r.Type
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (r *Repository) GetURL() string {
	if r == nil || r.URL == nil {
		return ""
	}
	return *r.URL
}

// GetAdmin returns the Admin field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetAdmin() bool {
	if s == nil || s.Admin == nil {
		return false
	}
	return *s.Admin
}

// GetDisableUIAccess returns the DisableUIAccess field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetDisableUIAccess() bool {
	if s == nil || s.DisableUIAccess == nil {
		return false
	}
	return *s.DisableUIAccess
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetEmail() string {
	if s == nil || s.Email == nil {
		return ""
	}
	return *s.Email
}

// GetGroups returns the Groups field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetGroups() []string {
	if s == nil || s.Groups == nil {
		return nil
	}
	return *s.Groups
}

// GetInternalPasswordDisabled returns the InternalPasswordDisabled field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetInternalPasswordDisabled() bool {
	if s == nil || s.InternalPasswordDisabled == nil {
		return false
	}
	return *s.InternalPasswordDisabled
}

// GetLastLoggedIn returns the LastLoggedIn field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetLastLoggedIn() string {
	if s == nil || s.LastLoggedIn == nil {
		return ""
	}
	return *s.LastLoggedIn
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetPassword returns the Password field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetPassword() string {
	if s == nil || s.Password == nil {
		return ""
	}
	return *s.Password
}

// GetProfileUpdatable returns the ProfileUpdatable field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetProfileUpdatable() bool {
	if s == nil || s.ProfileUpdatable == nil {
		return false
	}
	return *s.ProfileUpdatable
}

// GetRealm returns the Realm field if it's non-nil, zero value otherwise.
func (s *SecurityUser) GetRealm() string {
	if s == nil || s.Realm == nil {
		return ""
	}
	return *s.Realm
}

// GetBinariesSummary returns the BinariesSummary field.
func (s *StorageSummary) GetBinariesSummary() *BinariesSummary {
	if s == nil {
		return nil
	}
	return s.BinariesSummary
}

// GetFileStoreSummary returns the FileStoreSummary field.
func (s *StorageSummary) GetFileStoreSummary() *FileStoreSummary {
	if s == nil {
		return nil
	}
	return s.FileStoreSummary
}

// GetRepositoriesSummaryList returns the RepositoriesSummaryList field if it's non-nil, zero value otherwise.
func (s *StorageSummary) GetRepositoriesSummaryList() []RepositoriesSummary {
	if s == nil || s.RepositoriesSummaryList == nil {
		return nil
	}
	return *s.RepositoriesSummaryList
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *Tags) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetTags returns the Tags field if it's non-nil, zero value otherwise.
func (t *Tags) GetTags() []string {
	if t == nil || t.Tags == nil {
		return nil
	}
	return *t.Tags
}

// GetAdmin returns the Admin field if it's non-nil, zero value otherwise.
func (u *User) GetAdmin() bool {
	if u == nil || u.Admin == nil {
		return false
	}
	return *u.Admin
}

// GetCredentialsExpired returns the CredentialsExpired field if it's non-nil, zero value otherwise.
func (u *User) GetCredentialsExpired() bool {
	if u == nil || u.CredentialsExpired == nil {
		return false
	}
	return *u.CredentialsExpired
}

// GetDisableUIAccess returns the DisableUIAccess field if it's non-nil, zero value otherwise.
func (u *User) GetDisableUIAccess() bool {
	if u == nil || u.DisableUIAccess == nil {
		return false
	}
	return *u.DisableUIAccess
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *User) GetEmail() string {
	if u == nil || u.Email == nil {
		return ""
	}
	return *u.Email
}

// GetExistsInDB returns the ExistsInDB field if it's non-nil, zero value otherwise.
func (u *User) GetExistsInDB() bool {
	if u == nil || u.ExistsInDB == nil {
		return false
	}
	return *u.ExistsInDB
}

// GetExternalRealmLink returns the ExternalRealmLink field if it's non-nil, zero value otherwise.
func (u *User) GetExternalRealmLink() string {
	if u == nil || u.ExternalRealmLink == nil {
		return ""
	}
	return *u.ExternalRealmLink
}

// GetGroupAdmin returns the GroupAdmin field if it's non-nil, zero value otherwise.
func (u *User) GetGroupAdmin() bool {
	if u == nil || u.GroupAdmin == nil {
		return false
	}
	return *u.GroupAdmin
}

// GetGroups returns the Groups field if it's non-nil, zero value otherwise.
func (u *User) GetGroups() []string {
	if u == nil || u.Groups == nil {
		return nil
	}
	return *u.Groups
}

// GetHideUploads returns the HideUploads field if it's non-nil, zero value otherwise.
func (u *User) GetHideUploads() bool {
	if u == nil || u.HideUploads == nil {
		return false
	}
	return *u.HideUploads
}

// GetInternalPasswordDisabled returns the InternalPasswordDisabled field if it's non-nil, zero value otherwise.
func (u *User) GetInternalPasswordDisabled() bool {
	if u == nil || u.InternalPasswordDisabled == nil {
		return false
	}
	return *u.InternalPasswordDisabled
}

// GetLastLoggedIn returns the LastLoggedIn field if it's non-nil, zero value otherwise.
func (u *User) GetLastLoggedIn() string {
	if u == nil || u.LastLoggedIn == nil {
		return ""
	}
	return *u.LastLoggedIn
}

// GetLastLoggedInMillis returns the LastLoggedInMillis field if it's non-nil, zero value otherwise.
func (u *User) GetLastLoggedInMillis() int64 {
	if u == nil || u.LastLoggedInMillis == nil {
		return 0
	}
	return *u.LastLoggedInMillis
}

// GetLocked returns the Locked field if it's non-nil, zero value otherwise.
func (u *User) GetLocked() bool {
	if u == nil || u.Locked == nil {
		return false
	}
	return *u.Locked
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (u *User) GetName() string {
	if u == nil || u.Name == nil {
		return ""
	}
	return *u.Name
}

// GetNumberOfGroups returns the NumberOfGroups field if it's non-nil, zero value otherwise.
func (u *User) GetNumberOfGroups() int {
	if u == nil || u.NumberOfGroups == nil {
		return 0
	}
	return *u.NumberOfGroups
}

// GetNumberOfPermissions returns the NumberOfPermissions field if it's non-nil, zero value otherwise.
func (u *User) GetNumberOfPermissions() int {
	if u == nil || u.NumberOfPermissions == nil {
		return 0
	}
	return *u.NumberOfPermissions
}

// GetOfflineMode returns the OfflineMode field if it's non-nil, zero value otherwise.
func (u *User) GetOfflineMode() bool {
	if u == nil || u.OfflineMode == nil {
		return false
	}
	return *u.OfflineMode
}

// GetProfileUpdatable returns the ProfileUpdatable field if it's non-nil, zero value otherwise.
func (u *User) GetProfileUpdatable() bool {
	if u == nil || u.ProfileUpdatable == nil {
		return false
	}
	return *u.ProfileUpdatable
}

// GetProWithoutLicense returns the ProWithoutLicense field if it's non-nil, zero value otherwise.
func (u *User) GetProWithoutLicense() bool {
	if u == nil || u.ProWithoutLicense == nil {
		return false
	}
	return *u.ProWithoutLicense
}

// GetRealm returns the Realm field if it's non-nil, zero value otherwise.
func (u *User) GetRealm() string {
	if u == nil || u.Realm == nil {
		return ""
	}
	return *u.Realm
}

// GetRequireProfilePassword returns the RequireProfilePassword field if it's non-nil, zero value otherwise.
func (u *User) GetRequireProfilePassword() bool {
	if u == nil || u.RequireProfilePassword == nil {
		return false
	}
	return *u.RequireProfilePassword
}

// GetRequireProfileUnlock returns the RequireProfileUnlock field if it's non-nil, zero value otherwise.
func (u *User) GetRequireProfileUnlock() bool {
	if u == nil || u.RequireProfileUnlock == nil {
		return false
	}
	return *u.RequireProfileUnlock
}

// GetAddons returns the Addons field if it's non-nil, zero value otherwise.
func (v *Versions) GetAddons() []string {
	if v == nil || v.Addons == nil {
		return nil
	}
	return *v.Addons
}

// GetRevision returns the Revision field if it's non-nil, zero value otherwise.
func (v *Versions) GetRevision() string {
	if v == nil || v.Revision == nil {
		return ""
	}
	return *v.Revision
}

// GetVersion returns the Version field if it's non-nil, zero value otherwise.
func (v *Versions) GetVersion() string {
	if v == nil || v.Version == nil {
		return ""
	}
	return *v.Version
}

// GetArtifactoryRequestsCanRetrieveRemoteArtifacts returns the ArtifactoryRequestsCanRetrieveRemoteArtifacts field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetArtifactoryRequestsCanRetrieveRemoteArtifacts() bool {
	if v == nil || v.ArtifactoryRequestsCanRetrieveRemoteArtifacts == nil {
		return false
	}
	return *v.ArtifactoryRequestsCanRetrieveRemoteArtifacts
}

// GetDebianTrivialLayout returns the DebianTrivialLayout field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetDebianTrivialLayout() bool {
	if v == nil || v.DebianTrivialLayout == nil {
		return false
	}
	return *v.DebianTrivialLayout
}

// GetDefaultDeploymentRepo returns the DefaultDeploymentRepo field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetDefaultDeploymentRepo() string {
	if v == nil || v.DefaultDeploymentRepo == nil {
		return ""
	}
	return *v.DefaultDeploymentRepo
}

// GetKeyPair returns the KeyPair field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetKeyPair() string {
	if v == nil || v.KeyPair == nil {
		return ""
	}
	return *v.KeyPair
}

// GetPomRepositoryReferencesCleanupPolicy returns the PomRepositoryReferencesCleanupPolicy field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetPomRepositoryReferencesCleanupPolicy() string {
	if v == nil || v.PomRepositoryReferencesCleanupPolicy == nil {
		return ""
	}
	return *v.PomRepositoryReferencesCleanupPolicy
}

// GetRepositories returns the Repositories field if it's non-nil, zero value otherwise.
func (v *VirtualRepository) GetRepositories() []string {
	if v == nil || v.Repositories == nil {
		return nil
	}
	return *v.Repositories
}
