// Copyright (c) 2018 Target Brands, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by gen-accessors; DO NOT EDIT.

package xray

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *Ping) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (s *ScanAlert) GetCreated() Timestamp {
	if s == nil || s.Created == nil {
		return Timestamp{}
	}
	return *s.Created
}

// GetIssues returns the Issues field if it's non-nil, zero value otherwise.
func (s *ScanAlert) GetIssues() []ScanIssue {
	if s == nil || s.Issues == nil {
		return nil
	}
	return *s.Issues
}

// GetTopSeverity returns the TopSeverity field if it's non-nil, zero value otherwise.
func (s *ScanAlert) GetTopSeverity() string {
	if s == nil || s.TopSeverity == nil {
		return ""
	}
	return *s.TopSeverity
}

// GetWatchName returns the WatchName field if it's non-nil, zero value otherwise.
func (s *ScanAlert) GetWatchName() string {
	if s == nil || s.WatchName == nil {
		return ""
	}
	return *s.WatchName
}

// GetChecksum returns the Checksum field.
func (s *ScanArtifactRequest) GetChecksum() *ScanChecksum {
	if s == nil {
		return nil
	}
	return s.Checksum
}

// GetComponentID returns the ComponentID field if it's non-nil, zero value otherwise.
func (s *ScanArtifactRequest) GetComponentID() string {
	if s == nil || s.ComponentID == nil {
		return ""
	}
	return *s.ComponentID
}

// GetSummary returns the Summary field if it's non-nil, zero value otherwise.
func (s *ScanArtifactRequest) GetSummary() string {
	if s == nil || s.Summary == nil {
		return ""
	}
	return *s.Summary
}

// GetInfo returns the Info field if it's non-nil, zero value otherwise.
func (s *ScanArtifactResponse) GetInfo() string {
	if s == nil || s.Info == nil {
		return ""
	}
	return *s.Info
}

// GetAlertType returns the AlertType field if it's non-nil, zero value otherwise.
func (s *ScanBannedLicense) GetAlertType() string {
	if s == nil || s.AlertType == nil {
		return ""
	}
	return *s.AlertType
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *ScanBannedLicense) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (s *ScanBannedLicense) GetSeverity() string {
	if s == nil || s.Severity == nil {
		return ""
	}
	return *s.Severity
}

// GetSummary returns the Summary field if it's non-nil, zero value otherwise.
func (s *ScanBannedLicense) GetSummary() string {
	if s == nil || s.Summary == nil {
		return ""
	}
	return *s.Summary
}

// GetArtifactoryID returns the ArtifactoryID field if it's non-nil, zero value otherwise.
func (s *ScanBuildRequest) GetArtifactoryID() string {
	if s == nil || s.ArtifactoryID == nil {
		return ""
	}
	return *s.ArtifactoryID
}

// GetBuildName returns the BuildName field if it's non-nil, zero value otherwise.
func (s *ScanBuildRequest) GetBuildName() string {
	if s == nil || s.BuildName == nil {
		return ""
	}
	return *s.BuildName
}

// GetBuildNumber returns the BuildNumber field if it's non-nil, zero value otherwise.
func (s *ScanBuildRequest) GetBuildNumber() string {
	if s == nil || s.BuildNumber == nil {
		return ""
	}
	return *s.BuildNumber
}

// GetAlerts returns the Alerts field if it's non-nil, zero value otherwise.
func (s *ScanBuildResponse) GetAlerts() []ScanAlert {
	if s == nil || s.Alerts == nil {
		return nil
	}
	return *s.Alerts
}

// GetLicenses returns the Licenses field if it's non-nil, zero value otherwise.
func (s *ScanBuildResponse) GetLicenses() []ScanLicense {
	if s == nil || s.Licenses == nil {
		return nil
	}
	return *s.Licenses
}

// GetSummary returns the Summary field.
func (s *ScanBuildResponse) GetSummary() *ScanSummary {
	if s == nil {
		return nil
	}
	return s.Summary
}

// GetMd5 returns the Md5 field if it's non-nil, zero value otherwise.
func (s *ScanChecksum) GetMd5() string {
	if s == nil || s.Md5 == nil {
		return ""
	}
	return *s.Md5
}

// GetSha1 returns the Sha1 field if it's non-nil, zero value otherwise.
func (s *ScanChecksum) GetSha1() string {
	if s == nil || s.Sha1 == nil {
		return ""
	}
	return *s.Sha1
}

// GetSha256 returns the Sha256 field if it's non-nil, zero value otherwise.
func (s *ScanChecksum) GetSha256() string {
	if s == nil || s.Sha256 == nil {
		return ""
	}
	return *s.Sha256
}

// GetBannedLicenses returns the BannedLicenses field if it's non-nil, zero value otherwise.
func (s *ScanDetail) GetBannedLicenses() []ScanBannedLicense {
	if s == nil || s.BannedLicenses == nil {
		return nil
	}
	return *s.BannedLicenses
}

// GetChild returns the Child field if it's non-nil, zero value otherwise.
func (s *ScanDetail) GetChild() string {
	if s == nil || s.Child == nil {
		return ""
	}
	return *s.Child
}

// GetVulnerabilities returns the Vulnerabilities field if it's non-nil, zero value otherwise.
func (s *ScanDetail) GetVulnerabilities() []ScanVulnerability {
	if s == nil || s.Vulnerabilities == nil {
		return nil
	}
	return *s.Vulnerabilities
}

// GetDepth returns the Depth field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetDepth() string {
	if s == nil || s.Depth == nil {
		return ""
	}
	return *s.Depth
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetDisplayName() string {
	if s == nil || s.DisplayName == nil {
		return ""
	}
	return *s.DisplayName
}

// GetInfectedFiles returns the InfectedFiles field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetInfectedFiles() []ScanInfectedFile {
	if s == nil || s.InfectedFiles == nil {
		return nil
	}
	return *s.InfectedFiles
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetParentSha returns the ParentSha field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetParentSha() string {
	if s == nil || s.ParentSha == nil {
		return ""
	}
	return *s.ParentSha
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetPath() string {
	if s == nil || s.Path == nil {
		return ""
	}
	return *s.Path
}

// GetPkgType returns the PkgType field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetPkgType() string {
	if s == nil || s.PkgType == nil {
		return ""
	}
	return *s.PkgType
}

// GetSha1 returns the Sha1 field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetSha1() string {
	if s == nil || s.Sha1 == nil {
		return ""
	}
	return *s.Sha1
}

// GetSha256 returns the Sha256 field if it's non-nil, zero value otherwise.
func (s *ScanImpactedArtifact) GetSha256() string {
	if s == nil || s.Sha256 == nil {
		return ""
	}
	return *s.Sha256
}

// GetComponentID returns the ComponentID field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetComponentID() string {
	if s == nil || s.ComponentID == nil {
		return ""
	}
	return *s.ComponentID
}

// GetDepth returns the Depth field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetDepth() string {
	if s == nil || s.Depth == nil {
		return ""
	}
	return *s.Depth
}

// GetDetails returns the Details field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetDetails() []ScanDetail {
	if s == nil || s.Details == nil {
		return nil
	}
	return *s.Details
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetDisplayName() string {
	if s == nil || s.DisplayName == nil {
		return ""
	}
	return *s.DisplayName
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetParentSha returns the ParentSha field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetParentSha() string {
	if s == nil || s.ParentSha == nil {
		return ""
	}
	return *s.ParentSha
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetPath() string {
	if s == nil || s.Path == nil {
		return ""
	}
	return *s.Path
}

// GetPkgType returns the PkgType field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetPkgType() string {
	if s == nil || s.PkgType == nil {
		return ""
	}
	return *s.PkgType
}

// GetSha1 returns the Sha1 field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetSha1() string {
	if s == nil || s.Sha1 == nil {
		return ""
	}
	return *s.Sha1
}

// GetSha256 returns the Sha256 field if it's non-nil, zero value otherwise.
func (s *ScanInfectedFile) GetSha256() string {
	if s == nil || s.Sha256 == nil {
		return ""
	}
	return *s.Sha256
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetCreated() Timestamp {
	if s == nil || s.Created == nil {
		return Timestamp{}
	}
	return *s.Created
}

// GetCve returns the Cve field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetCve() string {
	if s == nil || s.Cve == nil {
		return ""
	}
	return *s.Cve
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetImpactedArtifacts returns the ImpactedArtifacts field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetImpactedArtifacts() []ScanImpactedArtifact {
	if s == nil || s.ImpactedArtifacts == nil {
		return nil
	}
	return *s.ImpactedArtifacts
}

// GetProvider returns the Provider field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetProvider() string {
	if s == nil || s.Provider == nil {
		return ""
	}
	return *s.Provider
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetSeverity() string {
	if s == nil || s.Severity == nil {
		return ""
	}
	return *s.Severity
}

// GetSummary returns the Summary field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetSummary() string {
	if s == nil || s.Summary == nil {
		return ""
	}
	return *s.Summary
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (s *ScanIssue) GetType() string {
	if s == nil || s.Type == nil {
		return ""
	}
	return *s.Type
}

// GetComponents returns the Components field if it's non-nil, zero value otherwise.
func (s *ScanLicense) GetComponents() []string {
	if s == nil || s.Components == nil {
		return nil
	}
	return *s.Components
}

// GetFullName returns the FullName field if it's non-nil, zero value otherwise.
func (s *ScanLicense) GetFullName() string {
	if s == nil || s.FullName == nil {
		return ""
	}
	return *s.FullName
}

// GetMoreInfoURL returns the MoreInfoURL field if it's non-nil, zero value otherwise.
func (s *ScanLicense) GetMoreInfoURL() []string {
	if s == nil || s.MoreInfoURL == nil {
		return nil
	}
	return *s.MoreInfoURL
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *ScanLicense) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetFailBuild returns the FailBuild field if it's non-nil, zero value otherwise.
func (s *ScanSummary) GetFailBuild() bool {
	if s == nil || s.FailBuild == nil {
		return false
	}
	return *s.FailBuild
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (s *ScanSummary) GetMessage() string {
	if s == nil || s.Message == nil {
		return ""
	}
	return *s.Message
}

// GetMoreDetailsURL returns the MoreDetailsURL field if it's non-nil, zero value otherwise.
func (s *ScanSummary) GetMoreDetailsURL() string {
	if s == nil || s.MoreDetailsURL == nil {
		return ""
	}
	return *s.MoreDetailsURL
}

// GetTotalAlerts returns the TotalAlerts field if it's non-nil, zero value otherwise.
func (s *ScanSummary) GetTotalAlerts() string {
	if s == nil || s.TotalAlerts == nil {
		return ""
	}
	return *s.TotalAlerts
}

// GetAlertType returns the AlertType field if it's non-nil, zero value otherwise.
func (s *ScanVulnerability) GetAlertType() string {
	if s == nil || s.AlertType == nil {
		return ""
	}
	return *s.AlertType
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *ScanVulnerability) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (s *ScanVulnerability) GetSeverity() string {
	if s == nil || s.Severity == nil {
		return ""
	}
	return *s.Severity
}

// GetSummary returns the Summary field if it's non-nil, zero value otherwise.
func (s *ScanVulnerability) GetSummary() string {
	if s == nil || s.Summary == nil {
		return ""
	}
	return *s.Summary
}

// GetGeneral returns the General field.
func (s *SummaryArtifact) GetGeneral() *SummaryGeneral {
	if s == nil {
		return nil
	}
	return s.General
}

// GetIssues returns the Issues field if it's non-nil, zero value otherwise.
func (s *SummaryArtifact) GetIssues() []SummaryIssue {
	if s == nil || s.Issues == nil {
		return nil
	}
	return *s.Issues
}

// GetLicenses returns the Licenses field if it's non-nil, zero value otherwise.
func (s *SummaryArtifact) GetLicenses() []SummaryLicense {
	if s == nil || s.Licenses == nil {
		return nil
	}
	return *s.Licenses
}

// GetChecksums returns the Checksums field if it's non-nil, zero value otherwise.
func (s *SummaryArtifactRequest) GetChecksums() []string {
	if s == nil || s.Checksums == nil {
		return nil
	}
	return *s.Checksums
}

// GetPaths returns the Paths field if it's non-nil, zero value otherwise.
func (s *SummaryArtifactRequest) GetPaths() []string {
	if s == nil || s.Paths == nil {
		return nil
	}
	return *s.Paths
}

// GetCve returns the Cve field if it's non-nil, zero value otherwise.
func (s *SummaryCve) GetCve() string {
	if s == nil || s.Cve == nil {
		return ""
	}
	return *s.Cve
}

// GetCvss2 returns the Cvss2 field if it's non-nil, zero value otherwise.
func (s *SummaryCve) GetCvss2() string {
	if s == nil || s.Cvss2 == nil {
		return ""
	}
	return *s.Cvss2
}

// GetCvss3 returns the Cvss3 field if it's non-nil, zero value otherwise.
func (s *SummaryCve) GetCvss3() string {
	if s == nil || s.Cvss3 == nil {
		return ""
	}
	return *s.Cvss3
}

// GetCwe returns the Cwe field if it's non-nil, zero value otherwise.
func (s *SummaryCve) GetCwe() []string {
	if s == nil || s.Cwe == nil {
		return nil
	}
	return *s.Cwe
}

// GetError returns the Error field if it's non-nil, zero value otherwise.
func (s *SummaryError) GetError() string {
	if s == nil || s.Error == nil {
		return ""
	}
	return *s.Error
}

// GetIdentifier returns the Identifier field if it's non-nil, zero value otherwise.
func (s *SummaryError) GetIdentifier() string {
	if s == nil || s.Identifier == nil {
		return ""
	}
	return *s.Identifier
}

// GetComponentID returns the ComponentID field if it's non-nil, zero value otherwise.
func (s *SummaryGeneral) GetComponentID() string {
	if s == nil || s.ComponentID == nil {
		return ""
	}
	return *s.ComponentID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SummaryGeneral) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (s *SummaryGeneral) GetPath() string {
	if s == nil || s.Path == nil {
		return ""
	}
	return *s.Path
}

// GetPkgType returns the PkgType field if it's non-nil, zero value otherwise.
func (s *SummaryGeneral) GetPkgType() string {
	if s == nil || s.PkgType == nil {
		return ""
	}
	return *s.PkgType
}

// GetSha256 returns the Sha256 field if it's non-nil, zero value otherwise.
func (s *SummaryGeneral) GetSha256() string {
	if s == nil || s.Sha256 == nil {
		return ""
	}
	return *s.Sha256
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetCreated() string {
	if s == nil || s.Created == nil {
		return ""
	}
	return *s.Created
}

// GetCves returns the Cves field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetCves() []SummaryCve {
	if s == nil || s.Cves == nil {
		return nil
	}
	return *s.Cves
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetImpactPath returns the ImpactPath field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetImpactPath() []string {
	if s == nil || s.ImpactPath == nil {
		return nil
	}
	return *s.ImpactPath
}

// GetIssueType returns the IssueType field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetIssueType() string {
	if s == nil || s.IssueType == nil {
		return ""
	}
	return *s.IssueType
}

// GetProvider returns the Provider field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetProvider() string {
	if s == nil || s.Provider == nil {
		return ""
	}
	return *s.Provider
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetSeverity() string {
	if s == nil || s.Severity == nil {
		return ""
	}
	return *s.Severity
}

// GetSummary returns the Summary field if it's non-nil, zero value otherwise.
func (s *SummaryIssue) GetSummary() string {
	if s == nil || s.Summary == nil {
		return ""
	}
	return *s.Summary
}

// GetComponents returns the Components field if it's non-nil, zero value otherwise.
func (s *SummaryLicense) GetComponents() []string {
	if s == nil || s.Components == nil {
		return nil
	}
	return *s.Components
}

// GetFullName returns the FullName field if it's non-nil, zero value otherwise.
func (s *SummaryLicense) GetFullName() string {
	if s == nil || s.FullName == nil {
		return ""
	}
	return *s.FullName
}

// GetMoreInfoURL returns the MoreInfoURL field if it's non-nil, zero value otherwise.
func (s *SummaryLicense) GetMoreInfoURL() []string {
	if s == nil || s.MoreInfoURL == nil {
		return nil
	}
	return *s.MoreInfoURL
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SummaryLicense) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetArtifacts returns the Artifacts field if it's non-nil, zero value otherwise.
func (s *SummaryResponse) GetArtifacts() []SummaryArtifact {
	if s == nil || s.Artifacts == nil {
		return nil
	}
	return *s.Artifacts
}

// GetErrors returns the Errors field if it's non-nil, zero value otherwise.
func (s *SummaryResponse) GetErrors() []SummaryError {
	if s == nil || s.Errors == nil {
		return nil
	}
	return *s.Errors
}

// GetAdmin returns the Admin field if it's non-nil, zero value otherwise.
func (u *User) GetAdmin() bool {
	if u == nil || u.Admin == nil {
		return false
	}
	return *u.Admin
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *User) GetEmail() string {
	if u == nil || u.Email == nil {
		return ""
	}
	return *u.Email
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (u *User) GetName() string {
	if u == nil || u.Name == nil {
		return ""
	}
	return *u.Name
}

// GetPassword returns the Password field if it's non-nil, zero value otherwise.
func (u *User) GetPassword() string {
	if u == nil || u.Password == nil {
		return ""
	}
	return *u.Password
}

// GetXrayRevision returns the XrayRevision field if it's non-nil, zero value otherwise.
func (v *Versions) GetXrayRevision() string {
	if v == nil || v.XrayRevision == nil {
		return ""
	}
	return *v.XrayRevision
}

// GetXrayVersion returns the XrayVersion field if it's non-nil, zero value otherwise.
func (v *Versions) GetXrayVersion() string {
	if v == nil || v.XrayVersion == nil {
		return ""
	}
	return *v.XrayVersion
}
