# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4

    - name: install go
      uses: actions/setup-go@v5
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: install
      run: |
        go get github.com/mattn/goveralls

    - name: exclude
      run: |
        rm -f artifactory/artifactory-accessors.go xray/xray-accessors.go # exclude generated code

    - name: test
      run: |
        go test -covermode=atomic -coverprofile=coverage.out ./...

    - name: coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
